swagger: '2.0'

info:
  version: '1.0.0'
  title: 'Activities'
  description: 'Microservice for creating, retrieving, updating, and deleting activities.'
  contact:
    name: Jarrod Parkes
    email: jarrod@udacity.com
    url: http://jarrodparkes.com
  license:
    name: MIT License
    
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
  
paths:
  /activities:
    get:
      description: Returns all activites.
      summary: Returns all activites.
      responses:
        200:
          description: Successful response.
          schema:
            type: array
            items:
              $ref: '#/definitions/Activity'
        400:
          $ref: "#/responses/BadRequest"
        401:
          $ref: "#/responses/Unauthorized"
        404:
          $ref: "#/responses/NotFound"
    post:
      description: Creates a new activity.
      summary: Creates a new activity.
      parameters:
        - name: activity
          in: body
          description: Data for a new activity.
          required: true
          schema:
            $ref: '#/definitions/Activity'
      responses:
        201:
          description: Resource created.
          schema:
            $ref: '#/definitions/Activity'
        400:
          $ref: "#/responses/BadRequest"            
        401:
          $ref: "#/responses/Unauthorized"
        404:
          $ref: "#/responses/NotFound"
  /activities/{id}:
    get:
      description: Returns activity with ID.
      summary: Returns activity with ID.
      parameters:
        - name: id
          in: path
          description: ID of activity to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response.
          schema:
            $ref: '#/definitions/Activity'
        400:
          $ref: "#/responses/BadRequest"            
        401:
          $ref: "#/responses/Unauthorized"
        404:
          $ref: "#/responses/NotFound"
    delete:
      description: Deletes activity with ID.
      summary: Deletes activity with ID.
      parameters:
        - name: id
          in: path
          description: ID of activity to delete
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: Successful response.
          schema:
            $ref: '#/definitions/Activity'
        401:
          $ref: "#/responses/Unauthorized"
        404:
          $ref: "#/responses/NotFound"

responses:
  BadRequest:
    description: Invalid request.
    schema:
      $ref: "#/definitions/Error"  
  NotFound:
    description: The specified resource was not found.
    schema:
      $ref: "#/definitions/Error"
  Unauthorized:
    description: Unauthorized.
    schema:
      $ref: "#/definitions/Error"

definitions:
  Activity:
    type: object
    properties:
      id:
        type: string
        description: ID of activity.
        readOnly: true
        example: "1"
      name:
        type: string
        description: Name of activity.
        example: "Monopoly"
      description:
        type: string
        description: Description of activity.
        example: "The fast-dealing property trading game."
      max_participants:
        type: integer
        description: Number of people who can participate in the activity.
        example: 4
    required:
      - name
      - description
      - max_participants
  Error:
    type: object
    properties:
      code:
        type: integer
        description: Error status code.
        format: int32
      message:
        type: string
        description: Error description.
    required:
      - code
      - message        
    example:
      code: 1
      message: "There was an error."