swagger: '2.0'

info:
  version: '1.0.0'
  title: 'Activities'
  description: 'Microservice for creating, retrieving, updating, and deleting activities.'
  contact:
    name: Jarrod Parkes
    email: jarrod@udacity.com
    url: http://jarrodparkes.com
  license:
    name: MIT License

schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /activities:
    get:
      description: Returns all activites.
      summary: Returns all activites.
      parameters:
        - name: pageSize
          in: path
          description: max number of activities to return
          required: false
          type: integer
          format: int64
        - name: offset
          in: path
          description: starting index of activities to return
          required: false
          type: integer
          format: int64
      responses:
        200:
          description: Successful response.
          schema:
            type: array
            items:
              $ref: '#/definitions/Activity'
        401:
          $ref: "#/responses/Unauthorized"
    post:
      description: Creates a new activity.
      summary: Creates a new activity.
      parameters:
        - name: activity
          in: body
          description: Data for a new activity.
          required: true
          schema:
            $ref: '#/definitions/NewActivity'
      responses:
        201:
          description: Activity created.
          schema:
            $ref: '#/definitions/Message'
        304:
          $ref: "#/responses/NotModified"            
        400:
          description: Bad request.
          schema:
            $ref: '#/definitions/Message'
        401:
          $ref: "#/responses/Unauthorized"
  /activities/{id}:
    get:
      description: Returns activity with ID.
      summary: Returns activity with ID.
      parameters:
        - name: id
          in: path
          description: ID of activity to fetch
          required: true
          type: integer
          format: int64
        - name: pageSize
          in: path
          description: max number of activities to return
          required: false
          type: integer
          format: int64
        - name: offset
          in: path
          description: starting index of activities to return
          required: false
          type: integer
          format: int64
      responses:
        200:
          description: Successful response.
          schema:
            $ref: '#/definitions/Activity'
        401:
          $ref: "#/responses/Unauthorized"
        404:
          $ref: "#/responses/NotFound"
    put:
      description: Updates and activity with ID.
      summary: Updates and activity with ID.
      parameters:
        - name: id
          in: path
          description: ID of activity to fetch
          required: true
          type: integer
          format: int64
        - name: activity
          in: body
          description: Data to update an existing activity.
          required: true
          schema:
            $ref: '#/definitions/NewActivity'  
      responses:
        200:
          description: Activity updated.
          schema:
            $ref: '#/definitions/Message'
        304:
          $ref: "#/responses/NotModified"            
        400:
          description: Bad request.
          schema:
            $ref: '#/definitions/Message'
        401:
          $ref: "#/responses/Unauthorized"            
    delete:
      description: Deletes activity with ID.
      summary: Deletes activity with ID.
      parameters:
        - name: id
          in: path
          description: ID of activity to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: Activity deleted.
          schema:
            $ref: '#/definitions/Message'
        304:
          $ref: "#/responses/NotModified"              
        400:
          description: Bad request.
          schema:
            $ref: '#/definitions/Message'           
        401:
          $ref: "#/responses/Unauthorized"

responses:
  NoContent:
    description: The request was fulfilled, but nothing to return.
  BadRequest:
    description: Invalid request.
  NotModified:
    description: The specified resource was not modified.
  NotFound:
    description: The specified resource was not found.
  Unauthorized:
    description: Unauthorized.

definitions:
  Activity:
    allOf:
      - $ref: '#/definitions/NewActivity'
      - required:
        - id
        properties:
          id:
            type: string
            description: ID of activity.
            readOnly: true
            default: "1"
  NewActivity:
    type: object
    properties:
      name:
        type: string
        description: Name of activity.
        default: "Monopoly"
      emoji:
        type: string
        description: Emoji representing activity.
        default: "⚔️"
      description:
        type: string
        description: Description of activity.
        default: "The fast-dealing property trading game."
      genre:
        type: string
        description: Genre of activity.
        default: "Adventure"
      min_participants:
        type: integer
        description: Minimum number of people who can participate in the activity.
        default: 2
      max_participants:
        type: integer
        description: Maximum number of people who can participate in the activity.
        default: 4
      created_at:
        type: string
        description: Date activity was created.
        format: YYYY-mm-dd HH:mm:ss
        default: "2017-07-24 20:43:51"
      updated_at:
        type: string
        description: Date activity was created.
        format: YYYY-mm-dd HH:mm:ss
        default: "2017-07-24 20:43:51"
    required:
      - name
      - emoji
      - description
      - genre
      - min_participants
      - max_participants
      - created_at
      - updated_at
  Message:
    type: object
    properties:
      message:
        type: string
        description: A message.
    required:
      - message
    example:
      message: "A message describing the HTTP status code."
