swagger: "2.0"
info:
  version: 1.0.0
  title: "chill-activities"
  description: This API is used for CRUD operations related to Chill activities.
  contact:
    name: Jarrod Parkes
    email: jarrod@udacity.com
    url: http://jarrodparkes.com
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
basePath: /api/activities
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /activities:
    get:
      description: Returns all activites.
      responses:
        200:
          description: activities response
          schema:
            type: array
            items:
              $ref: '#/definitions/Activity'
          examples:
            application/json: |-
              [
                {
                  "name": "Coffee n' Code",
                  "description": "Grab some brew and sling some code.",
                  "id": "1"
                },
                {
                  "name": "Minecraft",
                  "description": "Build worlds together.",
                  "id": "2"
                }
              ]
    post:
      description: Creates a new activity.
      parameters:
        - name: activity
          in: body
          description: Activity to add
          required: true
          schema:
            $ref: '#/definitions/NewActivity'
      responses:
        200:
          description: activity response
          schema:
            $ref: '#/definitions/Activity'
  /activities/{id}:
    get:
      description: Returns an activity based on a single ID.
      parameters:
        - name: id
          in: path
          description: ID of activity to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: activity response
          schema:
            $ref: '#/definitions/Activity'
    delete:
      description: Deletes an activity based on the ID supplied.
      parameters:
        - name: id
          in: path
          description: ID of activity to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: activity deleted
definitions:
  Activity:
    allOf:
      - $ref: '#/definitions/NewActivity'
      - required:
        - id
        properties:
          id:
            type: string
  NewActivity:
    required:
      - name
      - description
    properties:
      name:
        type: string
      description:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string