version: 2

defaults: &defaults
  working_directory: /tmp/activities
  docker:
    - image: ibmcom/kitura-ubuntu

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - setup_remote_docker:
          verison: 17.03.0-ce

      - run:
          name: Install Dependencies
          command: |
                  sudo apt-get update
                  sudo apt-get install -y curl libmysqlclient-dev

      - run:
          name: Build Application
          command: make web_build

      - persist_to_workspace:
          root: /tmp/
          paths:
            - activities


  unit_test:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          at: /tmp

      - run:
          name: Install Dependencies
          command: |
                  sudo apt-get update
                  sudo apt-get install -y libmysqlclient-dev

      - run:
          name: Unit Tests
          command: make web_unit_test

  functional_test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: /tmp
      - checkout

      - run:
          name: Install Dependencies
          command: |
                  sudo apt-get update
                  sudo apt-get install -y libmysqlclient-dev

      - run:
          name: Functional Tests
          command: make web_functional_test

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: /tmp

      - setup_remote_docker

      - run:
          name: Install Dependencies
          command: |
                  sudo apt-get update
                  sudo apt-get install -y curl libmysqlclient-dev

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Docker Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build production Docker image
          command: make web_release_build

      - run:
          name: Push image to Dockerhub
          command: |
            docker push udacity/activities-server:latest
            docker push udacity/activities-server:$(git rev-parse --short HEAD)

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - functional_test:
          requires:
            - build
      - deploy:
          requires:
            - unit_test
            - functional_test
          filters:
             branches:
               only: master