version: 2

jobs:
  build:
    working_directory: ~/activities
    
    docker:
      - image: ibmcom/kitura-ubuntu
    
    steps:
      - checkout

      - run: 
          name: Build Application
          command: make build

      - run: 
          name: Unit Tests
          command: make test

